services:
  - type: web
    name: north-banking
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from database import init_db; init_db()" && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
